# -*- coding: utf-8 -*-

"""Creación inicial de notificaciones

Revision ID: 18d670de1948
Revises: 113f8662d7a9
Create Date: 2015-10-29 12:35:44.075052

"""

# revision identifiers, used by Alembic.
revision = '18d670de1948'
down_revision = '113f8662d7a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('read_datetime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('notification_owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_owner_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_new_analysis_from_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_new_group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_membership_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_membership_id'], ['group_membership.id'], ),
    sa.ForeignKeyConstraint(['id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_new_shared_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_new_shared_analysis')
    op.drop_table('notification_new_group_membership')
    op.drop_table('notification_new_analysis_from_group')
    op.drop_table('notification')
    ### end Alembic commands ###
