# -*- coding: utf-8 -*-

"""Compartición de análisis a grupos

Revision ID: 1e8292ba7a17
Revises: 3230d077053a
Create Date: 2015-11-14 21:58:04.777901

"""

# revision identifiers, used by Alembic.
revision = '1e8292ba7a17'
down_revision = '3230d077053a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_permission')
    ### end Alembic commands ###
