# -*- coding: utf-8 -*-

"""Creación de notificaciones para comentarios de análisis

Revision ID: 1e8a829ba186
Revises: 1f38671f53c3
Create Date: 2015-11-01 23:18:08.881080

"""

# revision identifiers, used by Alembic.
revision = '1e8a829ba186'
down_revision = '1f38671f53c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_new_analysis_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_comment_id'], ['analysis_comment.id'], ),
    sa.ForeignKeyConstraint(['id'], ['notification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_new_analysis_comment')
    ### end Alembic commands ###
