"""empty message

Revision ID: 2316a04f895b
Revises: 1abd00e87462
Create Date: 2015-09-21 19:49:04.651659

"""

# revision identifiers, used by Alembic.
revision = '2316a04f895b'
down_revision = '1abd00e87462'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epicrisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('image_source_dir', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epicrisis')
    ### end Alembic commands ###
