"""Creación de la relación entre MeasurementType y MeasurementUnit

Revision ID: 309c776b77
Revises: 3923cd2bf565
Create Date: 2015-08-18 19:46:55.588186

"""

# revision identifiers, used by Alembic.
revision = '309c776b77'
down_revision = '3923cd2bf565'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_units_table',
    sa.Column('measurement_unit_id', sa.Integer(), nullable=False),
    sa.Column('measurement_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_type_id'], ['measurement_type.id'], ),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_unit.id'], ),
    sa.PrimaryKeyConstraint('measurement_unit_id', 'measurement_type_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurement_units_table')
    ### end Alembic commands ###
