# -*- coding: utf-8 -*-

"""Creación de epicrisis

Revision ID: 31a5c7944154
Revises: 545b51d61dcd
Create Date: 2015-10-06 12:18:21.654015

"""

# revision identifiers, used by Alembic.
revision = '31a5c7944154'
down_revision = '545b51d61dcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epicrisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=50), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('epicrisis')
    ### end Alembic commands ###
