# -*- coding: utf-8 -*-

"""Especificación del autor en notificaciones

Revision ID: 3230d077053a
Revises: 41779190aca3
Create Date: 2015-11-14 18:08:11.092247

"""

# revision identifiers, used by Alembic.
revision = '3230d077053a'
down_revision = '41779190aca3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notification_author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification', 'profile', ['notification_author_id'], ['id'])
    op.drop_constraint(u'notification_new_group_membership_profile_id_fkey', 'notification_new_group_membership', type_='foreignkey')
    op.drop_column('notification_new_group_membership', 'profile_id')
    op.drop_constraint(u'notification_new_shared_analysis_profile_id_fkey', 'notification_new_shared_analysis', type_='foreignkey')
    op.drop_column('notification_new_shared_analysis', 'profile_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_new_shared_analysis', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'notification_new_shared_analysis_profile_id_fkey', 'notification_new_shared_analysis', 'profile', ['profile_id'], ['id'])
    op.add_column('notification_new_group_membership', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'notification_new_group_membership_profile_id_fkey', 'notification_new_group_membership', 'profile', ['profile_id'], ['id'])
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'notification_author_id')
    ### end Alembic commands ###
