"""empty message

Revision ID: 3cc940260b9d
Revises: 2316a04f895b
Create Date: 2015-09-25 18:01:07.251069

"""

# revision identifiers, used by Alembic.
revision = '3cc940260b9d'
down_revision = '2316a04f895b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epicrisis', sa.Column('image_name', sa.String(length=50), nullable=True))
    op.drop_column('epicrisis', 'image_source_dir')
    op.drop_column('epicrisis', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epicrisis', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('epicrisis', sa.Column('image_source_dir', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('epicrisis', 'image_name')
    ### end Alembic commands ###
