# -*- coding: utf-8 -*-

"""Creación de validaciones para unidades de medición

Revision ID: 41779190aca3
Revises: 58858200b745
Create Date: 2015-11-10 22:39:29.714483

"""

# revision identifiers, used by Alembic.
revision = '41779190aca3'
down_revision = '58858200b745'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_unit_validation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('measurement_type_id', sa.Integer(), nullable=True),
    sa.Column('measurement_unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measurement_type_id'], ['measurement_type.id'], ),
    sa.ForeignKeyConstraint(['measurement_unit_id'], ['measurement_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('measurement_units_table')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement_units_table',
    sa.Column('measurement_unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('measurement_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['measurement_type_id'], [u'measurement_type.id'], name=u'measurement_units_table_measurement_type_id_fkey'),
    sa.ForeignKeyConstraint(['measurement_unit_id'], [u'measurement_unit.id'], name=u'measurement_units_table_measurement_unit_id_fkey'),
    sa.PrimaryKeyConstraint('measurement_unit_id', 'measurement_type_id', name=u'measurement_units_table_pkey')
    )
    op.drop_table('type_unit_validation')
    ### end Alembic commands ###
