# -*- coding: utf-8 -*-

"""Creación de permisos para comentarios de análisis

Revision ID: 4312431622eb
Revises: 3c6208d72ac0
Create Date: 2015-10-24 13:04:41.610208

"""

# revision identifiers, used by Alembic.
revision = '4312431622eb'
down_revision = '3c6208d72ac0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_type', sa.Column('can_edit_comments', sa.Boolean(), nullable=True))
    op.add_column('permission_type', sa.Column('can_view_comments', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission_type', 'can_view_comments')
    op.drop_column('permission_type', 'can_edit_comments')
    ### end Alembic commands ###
