# -*- coding: utf-8 -*-

"""Creación de atributo para usuarios administradores

Revision ID: 4afb778e6810
Revises: 1e8292ba7a17
Create Date: 2015-11-24 13:18:23.309280

"""

# revision identifiers, used by Alembic.
revision = '4afb778e6810'
down_revision = '1e8292ba7a17'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    ### end Alembic commands ###
