# -*- coding: utf-8 -*-

"""Creación de grupos de usuarios

Revision ID: 4ff3c8c6ba6f
Revises: 3c6208d72ac0
Create Date: 2015-10-25 19:41:11.034707

"""

# revision identifiers, used by Alembic.
revision = '4ff3c8c6ba6f'
down_revision = '3c6208d72ac0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_membership_type_id', sa.Integer(), nullable=True),
    sa.Column('permission_type_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['group_membership_type_id'], ['group_membership_type.id'], ),
    sa.ForeignKeyConstraint(['permission_type_id'], ['permission_type.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_membership')
    op.drop_table('group_membership_type')
    op.drop_table('group')
    ### end Alembic commands ###
