# -*- coding: utf-8 -*-

"""Manejo de archivos de análisis, y de credenciales a servicios de almacenamiento

Revision ID: 545b51d61dcd
Revises: 1abd00e87462
Create Date: 2015-09-26 20:12:43.607489

"""

# revision identifiers, used by Alembic.
revision = '545b51d61dcd'
down_revision = '1abd00e87462'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'measurement', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'measurement', 'analysis', ['analysis_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurement', type_='foreignkey')
    op.drop_column(u'measurement', 'analysis_id')
    op.drop_table('storage_credential')
    op.drop_table('analysis_file')
    op.drop_table('analysis')
    op.drop_table('storage_location')
    ### end Alembic commands ###
