# -*- coding: utf-8 -*-

"""Especificación de perfil de profesional médico

Revision ID: 58858200b745
Revises: 1e8a829ba186
Create Date: 2015-11-03 11:04:30.548565

"""

# revision identifiers, used by Alembic.
revision = '58858200b745'
down_revision = '1e8a829ba186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('is_health_professional', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'is_health_professional')
    ### end Alembic commands ###
